---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ralgar/homelab
        revision: feature/k8s-rework
        directories:
          - path: cluster/system/*
          - path: cluster/platform/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ralgar/homelab
        targetRevision: feature/k8s-rework
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 15m
        syncOptions:
          - CreateNamespace=true
