---
- name: Get CA certificate secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: "{{ net.domain }}"
    namespace: cert-manager
  register: ca_secret

- name: Print certificate
  ansible.builtin.copy:
    content: "{{ ca_secret.resources[0].data['root-cert.pem'] }}"
    dest: "/etc/ca-certificates/trust-source/anchors/{{ net.domain }}.pem"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Update CA trust store
  command: update-ca-trust
  become: true
