---
gitRepository:
  spec:
    url: ${repository}
    interval: 5m
    ref:
      name: ${ref_name}
      # Include an empty branch string to work around an issue where
      #  Flux defaults to refs/heads/master when no value is given.
      branch: ""
    recurseSubmodules: false

kustomization:
  spec:
    path: ${path}
    interval: 5m
    prune: true
    postBuild:
      substituteFrom:
          # Use this ConfigMap if it exists, but proceed if it doesn't.
        - kind: ConfigMap
          name: cluster-vars
          optional: true
          # Fail if this Secret does not exist.
        - kind: Secret
          name: cluster-secret-vars
