---
gitRepository:
  spec:
    url: ${repository}
    interval: 5m
    ref:
      name: ${ref_name}
      # Include an empty branch string to work around an issue where
      #  Flux defaults to refs/heads/master when no value is given.
      branch: ""
    recurseSubmodules: false

kustomization:
  spec:
    path: ${path}
    interval: 5m
    prune: true
