---
gitRepository:
  spec:
    url: ${repository}
    interval: 5m
    ref:
      name: ${ref_name}
      # Include an empty branch string to work around an issue where
      #  Flux defaults to refs/heads/master when no value is given.
      branch: ""
    recurseSubmodules: false

kustomization:
  spec:
    path: ${path}
    interval: 5m
    prune: true
    postBuild:
      substituteFrom:
          # Fail if these do not exist.
        - kind: ConfigMap
          name: cluster-config-vars
          optional: false
        - kind: Secret
          name: cluster-secret-vars
          optional: false
