---
- name: Assert the 'argo' Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Assert the 'argo-cd' Helm deployment
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: "{{ chart_version }}"
    namespace: argocd
    create_namespace: true
    update_repo_cache: true
    wait: true
    state: "{{ state | default('present') }}"

- name: Set path to local 'gitops-config' chart
  set_fact:
    config_chart: "{{ playbook_dir }}/cluster/bootstrap/gitops-config"

- name: Assert the 'config' Helm deployment
  kubernetes.core.helm:
    name: gitops-config
    chart_ref: "{{ config_chart }}"
    chart_version: "{{ chart_version }}"
    namespace: argocd
    wait: true
    values_files: "{{ config_chart }}/values.yaml"
    state: "{{ state | default('present') }}"

- name: Assert the namespace (for removal)
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
    state: absent
  when: state is defined and state == 'absent'
