---
- name: Install packages
  ansible.builtin.apt:
    name: bind9
    update_cache: true
    policy_rc_d: 101

- name: Install /etc/default/named
  ansible.builtin.copy:
    src: named
    dest: /etc/default/named
    owner: root
    group: root
    mode: 0644

- name: Include DNS master tasks
  include_tasks: master.yml
  when: ansible_hostname == 'ns1'

- name: Include DNS slave tasks
  include_tasks: slave.yml
  when: ansible_hostname >= 'ns2'

- name: Enable and start named service
  ansible.builtin.systemd:
    name: named
    enabled: true
    state: started
