---
- name: Install DNS slave configuration
  template:
    src: "{{ slave_files.src }}"
    dest: "{{ slave_files.dest }}"
    owner: root
    group: bind
    mode: 0640
  loop:
    - { src: named.conf.local.j2,   dest: /etc/bind/named.conf.local   }
    - { src: named.conf.options.j2, dest: /etc/bind/named.conf.options }
  loop_control:
    loop_var: slave_files
