---
- name: Install open-iscsi
  dnf:
    name: iscsi-initiator-utils
    update_cache: yes
    state: present
  when: packer_build_name == 'k3s-worker'

- name: Enable and start the iscsid service
  systemd:
    name: iscsid.service
    state: started
    enabled: yes
  when: packer_build_name == 'k3s-worker'
