# Deploys and provisions infrastructure services
---
- name: Deploy PostgreSQL Database with Terraform
  hosts: localhost
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.postgresql ]
      hostNums: [ 22 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision PostgreSQL Database with Ansible
  hosts: postgres
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - debian/postgresql

- name: Deploy PKI Server with Terraform
  hosts: localhost
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.pki-server ]
      hostNums: [ 24 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision PKI Server with Ansible
  hosts: pki_servers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - pki/cfssl-server

- name: Deploy LDAP server with Terraform
  hosts: localhost
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.ldap-server ]
      hostNums: [ 25 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision LDAP server with Ansible
  hosts: ldap_servers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - pki/import-root-ca
    - debian/389ds
