---
- name: Deploy Database with Terraform
  hosts: localhost
  vars_files:
    - vars/global.yml
  roles:
    - role: terraform-deploy
      targets: [ module.postgresql ]
      hostNums: [ 22 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision Database with Ansible
  hosts: postgres
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - common/upgrade-system
    - debian/postgresql
