# Deploys and provisions the infrastructure services
---
- name: Deploy Name Servers
  hosts: localhost
  vars_files:
    - vars/global.yml
  roles:
    - role: terraform-deploy
      targets: [ module.nameservers ]
      hostNums: "{{ dns.hostNums }}"
      targetNode: pve1
      storagePool: local-zfs

- name: Provision Name Servers
  hosts: new_nameservers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - common/upgrade-system
    - debian/nameserver

- name: Deploy Database
  hosts: localhost
  vars_files:
    - vars/global.yml
  roles:
    - role: terraform-deploy
      targets: [ module.postgresql ]
      hostNums: [ 22 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision Database
  hosts: postgres
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - common/upgrade-system
    - debian/postgresql
