# Deploys and provisions the K3s cluster
# Usage: ansible-playbook <playbook> [-e state=absent]
---
- name: Deploy K3s Cluster
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.k3s-master ]
      hostNums: [ 80 ]
      targetNode: pve1
      storagePool: local-zfs
    - role: proxmox/terraform-deploy
      targets: [ module.k3s-worker ]
      hostNums: [ 81 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision K3s Cluster
  hosts: k3s_cluster
  become: true
  gather_facts: false
  vars_files:
    - vars/global.yml
    - vars/pushover.yml
  roles:
    - role: common/wait-for-connection
    - role: common/wait-for-cloudinit
    - role: rhel8/automatic-upgrades
      when: "'k3s_workers' in group_names"
    - role: kubernetes/k3s-cluster

- name: Deploy Kubernetes applications
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/kubernetes.yml
  roles:
    - role: kubernetes/argo-cd
      when: state is not defined or state == 'present'
