# Deploys Kubernetes applications to the cluster
# Usage: ansible-playbook <playbook> [--tags <service-name>] [-e state=absent]
---
- name: Deploy Kubernetes applications
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/kubernetes.yml
  roles:
    - { role: kubernetes/gitlab-agent, tags: gitlab-agent }
