# Provisions X number of DNS nameservers,
#   depending on the number of hostNums supplied
---
- name: Deploy Name Servers with Terraform
  hosts: localhost
  vars_files:
    - vars/global.yml
  roles:
    - role: terraform-deploy
      targets: [ module.nameservers ]
      hostNums: "{{ dns.hostNums }}"    # Needs to be set in ./vars/global.yml
      targetNode: proxmox
      storagePool: local-zfs

- name: Provision Name Servers
  hosts: new_nameservers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - common/upgrade-system
    - debian/nameserver
