# Deploys and provisions GitLab and Runner(s)
---
- name: Deploy GitLab with Terraform
  hosts: localhost
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.gitlab ]
      hostNums: [ 30 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision GitLab with Ansible
  hosts: gitlab
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/gitlab.yml
  roles:
    - common/wait-for-connection
    - common/locale
    - pki/import-root-ca
    - gitlab/server

- name: Deploy the GitLab Runner VM with Terraform
  tags: runner
  hosts: localhost
  vars_files:
    - vars/hosts.proxmox.yml
    - vars/global.yml
  roles:
    - role: proxmox/terraform-deploy
      targets: [ module.gitlab-runner ]
      hostNums: [ 31 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision the GitLab Runner VM with Ansible
  tags: runner
  hosts: gitlab-runner
  become: true
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/gitlab.yml
  roles:
    - role: common/wait-for-connection
    - role: common/wait-for-cloudinit
    - role: rhel8/timesync-ntp
    - role: pki/import-root-ca
    - role: gitlab/runner
