---
- name: Deploy PKI with Terraform
  hosts: localhost
  vars_files:
    - vars/global.yml
  roles:
    - role: terraform-deploy
      targets: [ module.pki-server ]
      hostNums: [ 24 ]
      targetNode: pve1
      storagePool: local-zfs

- name: Provision PKI with Ansible
  hosts: pki_servers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/global.yml
  roles:
    - common/wait-for-connection
    - common/upgrade-system
    - pki/cfssl-server
