---
- name: Disable anonymous bind
  ldap_attrs:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: cn=config
    attributes:
      nsslapd-allow-anonymous-access: "off"
    state: exact
  notify: restart_dirsrv
