---
- name: Get TLS status
  stat:
    path: "/var/local/{{ ansible_hostname }}-chain.crt"
  register: dirsrv_cert_db

- name: Get Instance status
  stat:
    path: "/var/lib/dirsrv/slapd-{{ ansible_hostname }}"
  register: dirsrv_instance

- name: Install package(s)
  apt:
    pkg:
      - 389-ds-base
      - python3-cryptography
    install_recommends: no
    update_cache: yes
    policy_rc_d: 101

- name: Install the Directory Server
  include_tasks: bootstrap-database.yml
  when: not dirsrv_instance.stat.exists

- name: Include tasks
  include_tasks: "{{ item }}"
  loop:
    - authentication.yml
    - plugins/attribute-uniqueness.yml
    - plugins/dna.yml
    - plugins/enable-plugins.yml
    - permissions/user_read.yml
    - users/default-user.yml
    - groups/administrators.yml
    - configure-tls.yml
