---
- name: Ensure databases exist
  mysql_db:
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name:
      - coreprotect
      - floodgate
    encoding: utf8mb4
    state: present

- name: Ensure database user exists
  mysql_user:
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: mcserver
    host: '%'
    password: "{{ mcserver.dbpass }}"
    priv: "coreprotect.*:ALL"
    state: present
