---
- name: Ensure the volume(s) are present
  file:
    path: "/srv/{{ dir }}"
    state: directory
    owner: "10{{ service_uid }}"
    group: "10{{ service_uid }}"
    mode: 0700
  loop:
    - "{{ service_name }}"
    - "{{ service_name }}/config"
    - "{{ service_name }}/data/plugins/CoreProtect"
    - "{{ service_name }}/data/plugins/floodgate"
    - "{{ service_name }}/data/plugins/Geyser-Spigot"
    - "{{ service_name }}/data/plugins/HolographicDisplays"
  loop_control:
    loop_var: dir

- name: Install the mods list
  copy:
    src: mods.txt
    dest: "/srv/{{ service_name }}/config/mods.txt"
    owner: "10{{ service_uid }}"
    group: "10{{ service_uid }}"
    mode: 0600

- name: Install the plugin templates
  template:
    src: "config.{{ plugin }}.yml"
    dest: "/srv/{{ service_name }}/data/plugins/{{ plugin }}/config.yml"
    owner: "10{{ service_uid }}"
    group: "10{{ service_uid }}"
    mode: 0600
  loop:
    - CoreProtect
    - floodgate
    - Geyser-Spigot
    - HolographicDisplays
  loop_control:
    loop_var: plugin
