---
- name: Configure the DB
  postgresql_db:
    login_host: "postgres.{{ net.domain }}"
    login_user: dbadmin
    login_password: "{{ postgres.adminPassword }}"
    name: gitlabhq_production
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  delegate_to: localhost

- name: Configure the DB extensions
  postgresql_ext:
    login_host: "postgres.{{ net.domain }}"
    login_user: dbadmin
    login_password: "{{ postgres.adminPassword }}"
    name: "{{ gitlab_db_extensions }}"
    db: gitlabhq_production
    cascade: yes
    state: present
  delegate_to: localhost
  loop:
    - pg_trgm
    - btree_gist
    - plpgsql
  loop_control:
    loop_var: gitlab_db_extensions

- name: Configure the DB user
  postgresql_user:
    login_host: "postgres.{{ net.domain }}"
    login_user: dbadmin
    login_password: "{{ postgres.adminPassword }}"
    db: gitlabhq_production
    user: gitlab
    password: "p4$Sw0Rd"
    priv: "ALL"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
  delegate_to: localhost
