---
- name: Install Prerequisites
  apt:
    name:
      - apt-transport-https
      - gnupg
    update_cache: yes

- name: Install GitLab GPG Key
  apt_key:
    url: https://packages.gitlab.com/gpg.key

- name: Install GitLab '{{ edition | upper }}' Repositories
  apt_repository:
    repo: "{{ gitlab_repo }}"
    filename: gitlab
  loop:
    - "deb https://packages.gitlab.com/gitlab/gitlab-{{ edition }}/debian/ bullseye main"
    - "deb-src https://packages.gitlab.com/gitlab/gitlab-{{ edition }}/debian/ bullseye main"
  loop_control:
    loop_var: gitlab_repo

- name: Ensure GitLab config directory exists
  file:
    path: /etc/gitlab
    owner: root
    group: root
    mode: 0775
    state: directory

- name: Install GitLab config template
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart_gitlab

- name: Install GitLab
  apt:
    name: "gitlab-{{ edition }}"
    update_cache: yes
    state: present
  notify: ldap_handler
