---
- name: Get Root CA certificate (Red Hat)
  get_url:
    url: http://pki:8000/root-ca.pem
    dest: /etc/pki/ca-trust/source/anchors/homelab-root-ca.pem
  register: certificate_status

- name: Update CA trust store
  command: update-ca-trust
  when: certificate_status.changed
