---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nzbget-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: nzbget-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: adminPassword
      remoteRef:
        key: /mediasrv/nzbget
        property: adminPassword
    - secretKey: apiPassword
      remoteRef:
        key: /mediasrv/nzbget
        property: apiPassword
