---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
data:
  config.json: |-
    [
      {
        "clusterID": "a826fc5e-335d-4428-b7b4-14a02e082384",
        "monitors": [
          "192.168.1.10:6789"
        ]
      }
    ]
