---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  adminID: admin
  adminKey: AQCZIv1iyPddAxAAwlhKDUZlzg0pcbost162gA==
  userID: admin
  userKey: AQCZIv1iyPddAxAAwlhKDUZlzg0pcbost162gA==
