---
apiVersion: v1
kind: Secret
metadata:
  name: hass-restic-config
type: Opaque
stringData:
  RESTIC_REPOSITORY: gs:${GCP_BACKUP_BUCKET_NAME}:/volsync/hass
  RESTIC_PASSWORD: ${BACKUP_REPO_PASSWORD}
  GOOGLE_PROJECT_ID: ${GCP_BACKUP_PROJECT_ID}
data:
  # This value is base64 encoded by default
  GOOGLE_APPLICATION_CREDENTIALS: ${GCP_BACKUP_BUCKET_CREDS}
