---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin.homelab.internal
  namespace: media-server
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  commonName: jellyfin.homelab.internal
  dnsNames:
    - jellyfin.homelab.internal
    - jellyfin.jellyfin.svc
  issuerRef:
    name: internal-issuer
    kind: ClusterIssuer
  secretName: jellyfin-cert
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
    - name: jellyfin-http
      port: 8096
      protocol: TCP
      targetPort: jellyfin-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: media-server
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyfin.homelab.internal
      secretName: jellyfin-cert
  rules:
    - host: jellyfin.homelab.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  name: jellyfin-http
