---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyfin-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: jellyfin-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: jellyfin-server-id
      remoteRef:
        key: /mediasrv/jellyfin
        property: serverID
