---
- name: Install packages
  dnf:
    name:
      - "@container-tools:3.0/common"
      - bash-completion
      - python3-PyMySQL
      - vim-enhanced
    state: present

- name: Remove packages from prod server
  dnf:
    name:
      - cockpit-system
      - cockpit-ws
    autoremove: yes
    state: absent
  when: prod
