# Create and configure a rootless container user
---
- name: Clear ansible user subuid / subgid
  lineinfile:
    path: "{{ subfile }}"
    regexp: "^ansible"
    line: containers:100001:65536
  loop:
    - /etc/subuid
    - /etc/subgid
  loop_control:
    loop_var: subfile

- name: Create rootless user
  user:
    name: containers
    uid: 9000
    comment: "Runs rootless containers"
    system: yes
    createhome: yes
    shell: "{% if prod %}/sbin/nologin{% else %}/usr/bin/bash{% endif %}"
    #seuser: user_u
    state: present

- name: Check if user lingers
  stat:
    path: /var/lib/systemd/linger/containers
  register: linger

- name: Enable linger for user
  command: loginctl enable-linger containers
  when: not linger.stat.exists
