---
- name: Restart cfssl.service
  systemd:
    name: cfssl.service
    daemon_reload: yes
    state: restarted

- name: Restart ocsp.service
  systemd:
    name: ocsp.service
    daemon_reload: yes
    state: restarted

- name: Restart root-ca-serve.service
  systemd:
    name: root-ca-serve.service
    daemon_reload: yes
    state: restarted
