---
- name: Reconfigure and restart GitLab
  command: "{{ gitlab_restart_commands }}"
  loop:
    - gitlab-ctl reconfigure
    - gitlab-ctl restart
  loop_control:
    loop_var: gitlab_restart_commands
  when: gitlab_status.stat.exists
  listen: restart_gitlab

- name: Disable sign-up and standard auth
  include_tasks: ldap.yml
  listen: ldap_handler

- name: Create fullchain certificate
  shell: |
    cat /etc/gitlab/ssl/{{ ansible_hostname }}.{{ ansible_domain }}
    /etc/gitlab/trusted_certs/ca.crt
    > /etc/gitlab/ssl/gitlab-fullchain.crt
  listen: create_fullchain_certificate
