---
- name: Restart K3s service
  systemd:
    name: k3s.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create directory '~/.kube'
  file:
    path: ~/.kube
    state: directory
    mode: 0700
  delegate_to: localhost
  become: no
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Fetch kubeconfig from first master node
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    mode: 0600
    flat: yes
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Ensure FQDN is set correctly for kubeconfig
  replace:
    path: ~/.kube/config
    regexp: '127.0.0.1'
    replace: "{{ hostvars[groups['k3s_masters'][0]].ansible_hostname }}.{{ ansible_domain }}"
  delegate_to: localhost
  become: no
  when: inventory_hostname == groups['k3s_masters'][0]
