---
- name: Create 'administrators' group
  ldap_entry:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: "cn=administrators,ou=groups,{{ dirsrv_domain }}"
    objectClass:
      - top
      - groupOfNames
      - nsMemberOf
    attributes:
      cn: administrators
    state: present

- name: Assert 'administrators' group members
  ldap_attrs:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: "cn=administrators,ou=groups,{{ dirsrv_domain }}"
    attributes:
      member: "uid={{ default_user_uid }},ou=people,{{ dirsrv_domain }}"
    state: exact
