---
- name: 'Octavia : Install EPEL repository'
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: 'Octavia : Install system packages'
  ansible.builtin.dnf:
    name:
      - debootstrap
      - qemu-img
      - e2fsprogs
      - policycoreutils-python-utils
      - dhcp-client
    state: present
  become: true

- name: 'Octavia : Install venv dependencies'
  ansible.builtin.pip:
    name: diskimage-builder

- name: 'Octavia : Checkout image building source'
  ansible.builtin.git:
    repo: https://opendev.org/openstack/octavia.git
    dest: /root/octavia
    version: "stable/{{ openstack_release }}"
  notify: octavia
