---
- name: Assert system packages
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present
    update_cache: true

- name: Assert configuration file
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

- name: Assert notification script
  ansible.builtin.copy:
    src: pushover.sh
    dest: /usr/local/bin/pushover.sh
    owner: root
    group: root
    mode: 0700
    seuser: system_u
    serole: object_r
    setype: bin_t
    selevel: s0

- name: Assert systemd timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
