---
- name: Restart K3s service
  systemd:
    name: k3s.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create directory '~/.kube'
  file:
    path: ~/.kube
    state: directory
    mode: 0700
  delegate_to: localhost
  become: no

- name: Copy kubeconfig to local '~/.kube'
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    mode: 0600
    flat: yes

- name: Ensure FQDN is set correctly for kubeconfig
  ansible.builtin.lineinfile:
    path: ~/.kube/config
    regexp: '^    server:'
    line: "    server: https://{{ master_fqdn }}:6443"
  delegate_to: localhost
  become: no
