---
gitops:
  manifest_projects:
    - id: ralgar/homelab
      default_namespace: default
      paths:
        - glob: '/cluster/system/**/*.{yaml,yml,json}'
        - glob: '/cluster/platform/**/*.{yaml,yml,json}'
      dry_run_strategy: none
