---
- name: Install the systemd service files
  template:
    src: "{{ service_install }}"
    dest: "/usr/local/lib/systemd/system/{{ service_install }}"
    owner: root
    group: root
    mode: 0644
  notify: "Restart {{ service_install }}"
  loop:
    - cfssl.service
    - ocsp.service
    - root-ca-serve.service
  loop_control:
    loop_var: service_install

- name: Enable and Start the service
  systemd:
    name: "{{ service_start }}"
    enabled: yes
    state: started
  loop:
    - cfssl.service
    - ocsp.service
    - root-ca-serve.service
  loop_control:
    loop_var: service_start
