---
- name: Configure ELRepo Kernel repository
  yum_repository:
    name: elrepo-kernel
    description: ELRepo Kernel Respository
    baseurl:
      - "http://elrepo.org/linux/kernel/el8/$basearch"
      - "http://mirrors.coreix.net/elrepo/kernel/el8/$basearch"
      - "http://mirror.rackspace.com/elrepo/kernel/el8/$basearch"
      - "http://linux-mirrors.fnal.gov/linux/elrepo/kernel/el8/$basearch"
    mirrorlist: "http://mirrors.elrepo.org/mirrors-elrepo-kernel.el8"
    repo_gpgcheck: yes
    gpgcheck: yes
    gpgkey: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install LTS kernel
  dnf:
    name: kernel-lt
    state: present
    update_cache: yes
  notify: reboot_host
