---
- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: false

- name: Register runner with GitLab
  command: gitlab-runner register >
    --non-interactive
    --url "{{ runner_registration_url }}"
    --registration-token "{{ runner_registration_token }}"
    --description "{{ runner_description }}"
    --tag-list "{{ runner_tags | join(',') }}"
    --executor "{{ runner_executor }}"
    --docker-image "{{ runner_default_docker_image }}"
    --docker-privileged "true"
  when: configured_runners.stderr.find(runner_description) == -1

- name: Assert runner docker volumes
  lineinfile:
    path: /etc/gitlab-runner/config.toml
    insertafter: "[runners.docker]"
    search_string: "volumes ="
    line: '    volumes = ["/cache", "/dev/disk:/dev/disk"]'
  notify: restart_runner

- name: Assert runner docker devices
  lineinfile:
    path: /etc/gitlab-runner/config.toml
    insertafter: "[runners.docker]"
    search_string: "devices ="
    line: '    devices = ["/dev/sdb"]'
  notify: restart_runner
