---
- name: Include bootstrap tasks
  ansible.builtin.include_tasks: bootstrap.yml
  listen: bootstrap

- name: Generate Kolla passwords
  ansible.builtin.shell: |
    source {{ kolla_venv }}/bin/activate
    kolla-genpwd
  listen: generate_passwords

- name: 'Octavia : Include pre-deploy tasks'
  ansible.builtin.include_tasks: octavia/pre-deploy.yml
  listen: octavia

- name: Include precheck and deploy tasks
  ansible.builtin.include_tasks: kolla-deploy.yml
  listen: deploy

- name: Include post-deploy tasks
  ansible.builtin.include_tasks: post-deploy.yml
  listen: post_deploy

- name: 'Octavia : Include post-deploy tasks'
  ansible.builtin.include_tasks: octavia/post-deploy.yml
  listen: octavia
