---
- name: Generate '/etc/kolla/clouds.yaml'
  ansible.builtin.shell: |
    source {{ kolla_venv }}/bin/activate
    kolla-ansible post-deploy

- name: Fetch 'clouds.yaml' as an output
  ansible.builtin.fetch:
    src: /etc/kolla/clouds.yaml
    dest: "{% if ci_pipeline == 'true' %}{{ playbook_dir }}/tests/output/{% else %}{{ playbook_dir }}/output/{% endif %}"
    flat: true

- name: Set Nova to resume guest state after host reboot
  ansible.builtin.lineinfile:
    path: /etc/kolla/nova-compute/nova.conf
    insertafter: '^\[DEFAULT\]'
    regexp: '^resume_guests_state_on_host_boot'
    line: 'resume_guests_state_on_host_boot = True'
