[updates]
strategy = "periodic"

[updates.periodic]
time_zone = "America/Vancouver"

[[updates.periodic.window]]
days = [ "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" ]
start_time = "04:30"
length_minutes = 30
