---
- name: Upgrade the system
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  tags:
    - skip_ansible_lint

- name: Remove any orphaned dependencies
  ansible.builtin.dnf:
    autoremove: true
