---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sabnzbd-data-backup
  namespace: media-server
spec:
  sourcePVC: sabnzbd-data
  trigger:
    # @ 12:00pm UTC (4:00am PST / 5:00 am PDT)
    schedule: "0 12 * * *"
  restic:
    pruneIntervalDays: 7
    # Name of the Secret with the connection information
    repository: sabnzbd-restic-config
    retain:
      hourly: 6
      daily: 7
      weekly: 4
      monthly: 6
      yearly: 1
    copyMethod: Snapshot
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    storageClassName: cinder-standard
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: cinder-standard
    moverSecurityContext:
      runAsUser: 106789
      runAsGroup: 109030
      fsGroup: 109030
      seLinuxOptions:
        level: "s0:c123,c456"
