---
- name: "Swift : Fix 'auth_uri' for s3token"
  ansible.builtin.lineinfile:
    path: /etc/kolla/swift-proxy-server/proxy-server.conf
    insertafter: '^[filters:s3token]$'
    regexp: '^auth_uri ='
    line: "auth_uri = http://{{ ansible_default_ipv4.address }}:5000/v3"

- name: "Swift : Add 'swiftmember' role for 'keystoneauth' plugin"
  ansible.builtin.lineinfile:
    path: /etc/kolla/swift-proxy-server/proxy-server.conf
    insertafter: '^[filters:keystoneauth]$'
    regexp: '^operator_roles ='
    line: "operator_roles = admin,member,ResellerAdmin,swiftmember"

- name: "Swift : Create the 'swiftmember' role in Keystone"
  openstack.cloud.identity_role:
    name: swiftmember
    state: present
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
