---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dirsrv
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
spec:
  replicas: 1
  serviceName: jellyfin
  selector:
    matchLabels:
      app.kubernetes.io/name: 389ds
      app.kubernetes.io/instance: 389ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 389ds
        app.kubernetes.io/instance: 389ds
    spec:
      serviceAccountName: 389ds
      initContainers:
        - name: init
          image: ghcr.io/ralgar/389ds:2.4
          imagePullPolicy: IfNotPresent
          command: ["/config/init.sh"]
          env:
            - name: DS_SUFFIX_NAME
              value: "dc=homelab,dc=internal"
          volumeMounts:
            - name: 389ds-init-config
              mountPath: /config
            - name: 389ds-data
              mountPath: /data
            - name: 389ds-certs
              mountPath: /data/tls
              readOnly: true
            - name: 389ds-secrets
              mountPath: /secrets
          resources:
            limits:
              cpu: 2000m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 1000Mi
      containers:
        - name: 389ds
          image: ghcr.io/ralgar/389ds:2.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: ldap-tcp
              containerPort: 3389
              protocol: TCP
            - name: ldaps-tcp
              containerPort: 3636
              protocol: TCP
          volumeMounts:
            - name: 389ds-data
              mountPath: /data
            - name: 389ds-certs
              mountPath: /data/tls
              readOnly: true
          resources:
            limits:
              cpu: 2000m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 1000Mi
          livenessProbe:
            exec:
              command: ["/usr/bin/dscontainer", "-H"]
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["/usr/bin/dscontainer", "-H"]
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          startupProbe:
            exec:
              command: ["/usr/bin/dscontainer", "-H"]
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 10
          # TODO: Set security context
          # securityContext:
          #   runAsUser: 103389
          #   runAsGroup: 103389
          #   runAsNonRoot: true
          #   privileged: false
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
      volumes:
        - name: 389ds-init-config
          configMap:
            name: 389ds-init-config
            defaultMode: 0555
        - name: 389ds-data
          persistentVolumeClaim:
            claimName: 389ds-data
        - name: 389ds-certs
          secret:
            secretName: 389ds-cert
            items:
              - key: tls.key
                path: server.key
              - key: tls.crt
                path: server.crt
              - key: ca.crt
                path: ca/ca.crt
        - name: 389ds-secrets
          secret:
            secretName: 389ds-secrets
