---
apiVersion: v1
kind: Service
metadata:
  name: dirsrv
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: 3389
      protocol: TCP
      name: ldap-tcp
    - port: 636
      targetPort: 3636
      protocol: TCP
      name: ldaps-tcp
  selector:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
