---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap.homelab.internal
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
spec:
  commonName: ldap.homelab.internal
  dnsNames:
    - ldap.homelab.internal
    - dirsrv-0.dirsrv.389ds.svc
  issuerRef:
    name: internal-issuer
    kind: ClusterIssuer
  secretName: 389ds-cert
---
apiVersion: v1
kind: Service
metadata:
  name: dirsrv
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
  ports:
    - port: 3389
      targetPort: 3389
      protocol: TCP
      name: ldap-tcp
    - port: 3636
      targetPort: 3636
      protocol: TCP
      name: ldaps-tcp
