---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-data
  namespace: 389ds
spec:
  storageClassName: cinder-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
