---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      version: "4.x"
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/bitnami/charts/blob/main/bitnami/metallb/values.yaml
  values:
    prometheusRule:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          namespace: "monitoring"
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    speaker:
      metrics:
        enabled: true
        serviceMonitor:
          namespace: "monitoring"
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
