---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cinder-standard
  resources:
    requests:
      storage: 256Gi
