---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
parameters:
  type: "__DEFAULT__"
  fsType: xfs
