# Create a template VM in Proxmox
---
- name: Copy create-template.sh script
  copy:
    src: create-template.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0700

- name: Create a template using the script
  command:
    argv:
      - create-template.sh
      - "{{ item.template_name }}"
      - "/rpool/data/images/{{ item.image | basename }}"
      - zfs
  register: vm_template
  changed_when: vm_template.rc == 0
  failed_when: vm_template.rc == 2
