# Create a template VM in Proxmox
---
- name: "Fetch image : {{ item.image | basename }}"
  get_url:
    url: "{{ item.image }}"
    checksum: "{{ item.checksum }}"
    dest: "/rpool/data/images/{{ item.template_name }}.qcow2"
  register: image_status

- name: "Create template : {{ item.template_name }}"
  command:
    argv:
      - create-template.sh
      - "{{ item.template_name }}"
      - "/rpool/data/images/{{ item.template_name }}.qcow2"
      - local-zfs
  when: image_status.changed
