---
- name: Get kubeconfig from master node
  hosts: all
  remote_user: ansible
  gather_facts: false
  vars:
    k3s_kubeconfig_path: "~/.kube/config"
  tasks:
    - name: "Create local directory : '{{ k3s_kubeconfig_path | dirname }}'"
      ansible.builtin.file:
        path: "{{ k3s_kubeconfig_path | dirname }}"
        state: directory
        mode: 0700
      delegate_to: localhost
      become: false

    - name: Wait until kubeconfig is present before continuing
      ansible.builtin.wait_for:
        path: /etc/rancher/k3s/k3s.yaml
      become: true

    - name: Fetch kubeconfig from master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ k3s_kubeconfig_path }}"
        mode: 0600
        flat: true
      become: true

    - name: Ensure IP address is set correctly for kubeconfig
      ansible.builtin.replace:
        path: "{{ k3s_kubeconfig_path }}"
        regexp: '127.0.0.1'
        replace: "{{ k3s.controller.load_balancer_ip }}"
      delegate_to: localhost
      become: false
