---
timezone: UTC

mcserver:
  name: My New Minecraft Server
  motd: A PaperMC server for Java/Bedrock, running on 1.17.1
  version: 1.17.1
  max_players: 20
  dbpass: !unsafe p4$Sw0Rd
  ops: ''

mariadb_root_password: !unsafe p4$Sw0Rd

service_name: minecraft-server
service_uid: 1040                             # 1000-9999 range only
