---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-configmap
  namespace: media-server
data:
  init-db.sh: |
    #!/bin/bash

    set -xeu

    /entrypoint.sh 2>&1> /dev/null & disown
    pid=$!

    until timeout 300 curl -sf -o /dev/null \
        "localhost:8989/api/v3/system/status?apiKey=$SONARR__API_KEY"
    do
        sleep 1
    done

    kill $pid

  configure-db.sh: |
    #!/bin/bash

    set -xeu

    cp /configmaps/config.sql /config/config.sql || exit 1
    sed -i "s|nzbget-api-password|$(</secrets/nzbget-api-password)|" /config/config.sql || exit 1

    psql \
        -h "$POSTGRES_HOST" \
        -p "$POSTGRES_PORT" \
        -U "$POSTGRES_USER" \
        -d "$POSTGRES_DB" \
        -f /config/config.sql || exit 1

    rm -f /config/config.sql || exit 1

  config.sql: |
    INSERT INTO "DownloadClients" ("Id", "Enable", "Name", "Implementation", "Settings", "ConfigContract", "Priority", "RemoveCompletedDownloads", "RemoveFailedDownloads")
    VALUES ('1', '1', 'NZBGet', 'Nzbget', '{
      "host": "nzbget.media-server.svc",
      "port": 6789,
      "useSsl": false,
      "username": "api",
      "password": "nzbget-api-password",
      "tvCategory": "Series",
      "recentTvPriority": 0,
      "olderTvPriority": 0,
      "addPaused": false
    }', 'NzbgetSettings', '1', '1', '1')
    ON CONFLICT ("Id") DO UPDATE
        SET "Enable" = EXCLUDED."Enable",
            "Name" = EXCLUDED."Name",
            "Implementation" = EXCLUDED."Implementation",
            "Settings" = EXCLUDED."Settings",
            "ConfigContract" = EXCLUDED."ConfigContract",
            "Priority" = EXCLUDED."Priority",
            "RemoveCompletedDownloads" = EXCLUDED."RemoveCompletedDownloads",
            "RemoveFailedDownloads" = EXCLUDED."RemoveFailedDownloads";

    /* Set the media root directory */
    INSERT INTO "RootFolders" ("Id", "Path")
    VALUES('1', '/media/library/TV Shows')
    ON CONFLICT ("Id") DO UPDATE
        SET "Path" = EXCLUDED."Path";

    /* Enable renaming */
    INSERT INTO "NamingConfig" ("Id", "MultiEpisodeStyle", "RenameEpisodes", "StandardEpisodeFormat", "DailyEpisodeFormat", "SeasonFolderFormat", "SeriesFolderFormat", "AnimeEpisodeFormat", "ReplaceIllegalCharacters", "SpecialsFolderFormat")
    VALUES('1', '5', '1', '{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full}', '{Series Title} - {Air-Date} - {Episode Title} {Quality Full}', 'Season {season}', '{Series Title}', '{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Full}', '1', 'Specials')
    ON CONFLICT ("Id") DO UPDATE
        SET "MultiEpisodeStyle" = EXCLUDED."MultiEpisodeStyle",
            "RenameEpisodes" = EXCLUDED."RenameEpisodes",
            "StandardEpisodeFormat" = EXCLUDED."StandardEpisodeFormat",
            "DailyEpisodeFormat" = EXCLUDED."DailyEpisodeFormat",
            "SeasonFolderFormat" = EXCLUDED."SeasonFolderFormat",
            "SeriesFolderFormat" = EXCLUDED."SeriesFolderFormat",
            "AnimeEpisodeFormat" = EXCLUDED."AnimeEpisodeFormat",
            "ReplaceIllegalCharacters" = EXCLUDED."ReplaceIllegalCharacters",
            "SpecialsFolderFormat" = EXCLUDED."SpecialsFolderFormat";
