---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cephfs
  resources:
    requests:
      storage: 8Gi
