---
- name: Create 'user_read' permission
  ldap_entry:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: "cn=user_read,ou=permissions,{{ dirsrv_domain }}"
    objectClass:
      - top
      - groupOfNames
      - nsMemberOf
    attributes:
      cn: user_read
    state: present
