---
- name: Provision the K3s Cluster
  hosts: k3s_cluster
  become: true
  vars_files:
    - ../../vars/global.yml
  roles:
    - role: rhel8/timesync-ntp
    - role: rhel8/automatic-upgrades
      when: packer_build_name == 'k3s-worker'
    - role: kubernetes/k3s-cluster
