---
- name: Provision the K3s Cluster
  hosts: k3s_cluster
  become: true
  vars_files:
    - ../../vars/secret.yml
  roles:
    - role: rhel8/timesync-ntp
    - role: rhel8/automatic-upgrades
    - role: k3s-cluster
