---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  # TODO: Integrate with Prometheus
  # dependsOn:
  #   - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/ceph-csi
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
