---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 60m
  path: ./cluster/system/olm
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  dependsOn:
    - name: olm
  interval: 60m
  path: ./cluster/system/operators
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
