---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-data
  namespace: 389ds
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
