---
- name: Get CA certificate secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: "{{ net_root_domain }}"
    namespace: cert-manager
  register: ca_secret

- name: Create local CA certificate file from secret
  ansible.builtin.copy:
    content: "{{ ca_secret.resources[0].data['root-cert.pem'] }}"
    dest: "/etc/ca-certificates/trust-source/anchors/{{ net_root_domain }}.pem"
    owner: root
    group: root
    mode: 0644
  become: true
  notify: update_ca_trust_store
