---
- name: Create default compute flavors
  openstack.cloud.compute_flavor:
    name: "{{ item.name }}"
    vcpus: "{{ item.vcpus }}"
    ram: "{{ item.ram }}"
    disk: "{{ item.disk }}"
    state: present
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  loop:
    - { name: m1.tiny,   vcpus: 1, ram: 512,   disk: 0 }  # noqa: yaml[braces]
    - { name: m1.small,  vcpus: 1, ram: 2048,  disk: 0 }  # noqa: yaml[braces]
    - { name: m1.medium, vcpus: 2, ram: 4096,  disk: 0 }  # noqa: yaml[braces]
    - { name: m1.large,  vcpus: 4, ram: 8192,  disk: 0 }  # noqa: yaml[braces]
    - { name: m1.xlarge, vcpus: 8, ram: 16384, disk: 0 }  # noqa: yaml[braces]
