---
- name: Create temporary image downloads directory
  ansible.builtin.tempfile:
    state: directory
    suffix: image-downloads
  register: tempdir

- name: Download a Fedora CoreOS image
  ansible.builtin.command:
    argv:
      - curl
      - -Lo
      - "{{ tempdir.path }}/{{ openstack_fcos_image_temp_filename }}.xz"
      - "{{ openstack_fcos_image_url }}"
  args:
    creates: "{{ tempdir.path }}/{{ openstack_fcos_image_temp_filename }}.xz"

- name: Decompress the image
  ansible.builtin.command: "xz -d {{ tempdir.path }}/{{ openstack_fcos_image_temp_filename }}.xz"
  args:
    creates: "{{ tempdir.path }}/{{ openstack_fcos_image_temp_filename }}"

- name: Upload the image
  openstack.cloud.image:
    name: "{{ openstack_fcos_image_name }}"
    container_format: bare
    disk_format: qcow2
    filename: "{{ tempdir.path }}/{{ openstack_fcos_image_temp_filename }}"
    properties:
      os_distro: fedora-coreos
      os_version: "{{ openstack_fcos_image_version | string }}"
    min_disk: 10
    min_ram: 1536
    visibility: public
    checksum: "{{ openstack_fcos_image_decompressed_checksum }}"
    state: present
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: Remove the temporary image downloads directory
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent
  when: tempdir.path is defined
