---
# Run all / only tasks that use Ansible OpenStack modules after this
- name: Set Python interpreter to venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ kolla_venv }}/bin/python"

- name: Include tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - networks.yml
    - flavors.yml
    - projects.yml
