---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secrets
stringData:
  mosquitto.passwd: mqtt:$7$101$dT2KaKYNjdHVsuwd$iu89OvIcD+PanUBDDUrcCiO+QvkHNFisfQeVQK6LXWkfaj086h28np1AXSCMx1r+WKKEHhyZPI/Nh8tVKHKtRQ==
