---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: radarr
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: 107878
        runAsGroup: 109030
        fsGroup: 109030
      containers:
        - name: radarr
          image: "ghcr.io/onedr0p/radarr:4.7.5.7809"
          imagePullPolicy: IfNotPresent
          env:
            - name: RADARR__API_KEY
              valueFrom: { secretKeyRef: { name: radarr-secrets, key: apiKey } }
            - name: RADARR__POSTGRES_HOST
              valueFrom: { secretKeyRef: { name: mediasrv-pguser-radarr, key: host } }
            - name: RADARR__POSTGRES_PORT
              valueFrom: { secretKeyRef: { name: mediasrv-pguser-radarr, key: port } }
            - name: RADARR__POSTGRES_USER
              valueFrom: { secretKeyRef: { name: mediasrv-pguser-radarr, key: user } }
            - name: RADARR__POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: mediasrv-pguser-radarr, key: password } }
            - name: RADARR__POSTGRES_MAIN_DB
              value: radarr-main
            - name: RADARR__POSTGRES_LOG_DB
              value: radarr-log
            - name: RADARR__THEME
              value: dark
          ports:
            - name: radarr-http
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: radarr-data
              mountPath: /config
            - name: media
              mountPath: /media
          livenessProbe:
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while read -d
                \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: radarr-data
          emptyDir:
            sizeLimit: 16Mi
        - name: media
          persistentVolumeClaim:
            claimName: media
