---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-standard
  resources:
    requests:
      storage: 8Gi
