---
- name: Assert the K3s configuration file
  template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify: config_changed

- name: Assert the K3s service file
  template:
    src: k3s.service.j2
    dest: "{{ k3s_service_file }}"
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
    selevel: s0
  notify: config_changed

- name: Enable the K3s service
  systemd:
    name: k3s.service
    daemon_reload: yes
    enabled: yes
