---
- name: Create 'admin' user
  ldap_entry:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: "uid=admin,ou=people,{{ dirsrv_domain }}"
    objectClass:
      - top
      - nsPerson
      - nsAccount
      - nsOrgPerson
    attributes:
      cn: admin
      uid: admin
      displayName: Admin
      userPassword: "{{ admin_user_password }}"
    state: present

- name: Assert 'admin' user
  ldap_attrs:
    bind_dn: cn=manager
    bind_pw: "{{ dirsrv_root_pw }}"
    server_uri: "{% if dirsrv_cert_db.stat.exists %}ldaps://{% else %}ldap://{% endif %}"
    validate_certs: no
    dn: "uid=admin,ou=people,{{ dirsrv_domain }}"
    attributes:
      cn: admin
      uid: admin
      displayName: Admin
      employeeType: developer
    state: exact
