---
- name: "Cinder : Create 'PREMIUM' storage backend"
  ansible.builtin.blockinfile:
    path: "/etc/kolla/{{ cinder_create }}/cinder.conf"
    block: |
      [lvm-2]
      volume_group = cinder-premium
      volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
      volume_backend_name = lvm-2
      target_helper = lioadm
      target_protocol = iscsi
  loop:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
  loop_control:
    loop_var: cinder_create
  notify: restart_containers

- name: "Cinder : Enable the additonal backend(s)"
  ansible.builtin.lineinfile:
    path: "/etc/kolla/{{ cinder_enable }}/cinder.conf"
    insertafter: '^\[DEFAULT\]'
    regexp: '^enabled_backends'
    line: 'enabled_backends = lvm-1,lvm-2'
  loop:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
  loop_control:
    loop_var: cinder_enable
  notify: restart_containers
