---
- name: Set Python interpreter to venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ designate_kolla_venv }}/bin/python"

- name: Add upstream server configuration in 'named.conf'
  ansible.builtin.blockinfile:
    path: "/etc/kolla/designate-backend-bind9/named.conf"
    prepend_newline: true
    insertafter: 'recursion'
    block: |8  # This is fucking stupid, but it renders correctly.
                    forwarders {
                    {% for server in designate_upstream_servers %}
                    {{ server }};
                    {% endfor %}
            };
                    forward only;
    marker: "        // {mark} ANSIBLE MANAGED BLOCK"
  notify: designate_restart_bind9

- name: Enable recursion in 'named.conf'
  ansible.builtin.lineinfile:
    path: "/etc/kolla/designate-backend-bind9/named.conf"
    regexp: 'recursion'
    line: '        recursion yes;'
  notify: designate_restart_bind9

- name: Create the default zone
  openstack.cloud.dns_zone:
    name: "{{ designate_default_zone }}."
    description: Default zone
    email: "placeholder@{{ designate_default_zone }}"
    type: primary
    ttl: 3600
    state: present
    cloud: kolla-admin
    auth:
      project_name: prod
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
