---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap.homelab.internal
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
spec:
  commonName: ldap.homelab.internal
  dnsNames:
    - ldap.homelab.internal
    - dirsrv.389ds.svc
  issuerRef:
    name: internal-issuer
    kind: ClusterIssuer
  secretName: 389ds-cert
