---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 389ds
  namespace: 389ds
  labels:
    app.kubernetes.io/name: 389ds
    app.kubernetes.io/instance: 389ds
    app.kubernetes.io/version: "2.1"
