---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-server
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-cinder
    - name: external-secrets
    - name: ingress-nginx
    - name: trust-manager
    - name: vault
  interval: 60m
  path: ./cluster/apps/media-server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      MEDIA_VOLUME_ID: ${MEDIA_VOLUME_ID}
      MEDIA_VOLUME_SIZE: ${MEDIA_VOLUME_SIZE}
