---
- name: Restart all containers with a 'nova.conf' file
  community.docker.docker_container:
    name: "{{ nova_component | regex_replace('-', '_') }}"
    restart: true
  loop: "{{ nova_conf_components }}"
  loop_control:
    loop_var: nova_component
  listen: updated_nova_conf
